[I 09:23:22.862 NotebookApp] [nb_conda_kernels] enabled, 5 kernels found
[I 09:23:23.645 NotebookApp] [nb_conda] enabled
[I 09:23:23.646 NotebookApp] Serving notebooks from local directory: /home/lab15/git_repository/Study
[I 09:23:23.646 NotebookApp] The Jupyter Notebook is running at:
[I 09:23:23.646 NotebookApp] http://ip-172-31-41-188:8895/?token=9684a2c82eca6059edcec7afe5dc31be0b58a94ecd9f2939
[I 09:23:23.646 NotebookApp]  or http://127.0.0.1:8895/?token=9684a2c82eca6059edcec7afe5dc31be0b58a94ecd9f2939
[I 09:23:23.646 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:23:23.652 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/lab15/.local/share/jupyter/runtime/nbserver-6202-open.html
    Or copy and paste one of these URLs:
        http://ip-172-31-41-188:8895/?token=9684a2c82eca6059edcec7afe5dc31be0b58a94ecd9f2939
     or http://127.0.0.1:8895/?token=9684a2c82eca6059edcec7afe5dc31be0b58a94ecd9f2939
[I 09:32:16.572 NotebookApp] [nb_conda_kernels] enabled, 5 kernels found
[I 09:32:16.923 NotebookApp] [nb_conda] enabled
[I 09:32:16.923 NotebookApp] Serving notebooks from local directory: /home/lab15/git_repository/Study
[I 09:32:16.923 NotebookApp] The Jupyter Notebook is running at:
[I 09:32:16.923 NotebookApp] http://ip-172-31-41-188:8895/?token=40c26d1d7c73c00b635cbca8cf97c6aa2b78516d710512a3
[I 09:32:16.923 NotebookApp]  or http://127.0.0.1:8895/?token=40c26d1d7c73c00b635cbca8cf97c6aa2b78516d710512a3
[I 09:32:16.923 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:32:16.927 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/lab15/.local/share/jupyter/runtime/nbserver-6309-open.html
    Or copy and paste one of these URLs:
        http://ip-172-31-41-188:8895/?token=40c26d1d7c73c00b635cbca8cf97c6aa2b78516d710512a3
     or http://127.0.0.1:8895/?token=40c26d1d7c73c00b635cbca8cf97c6aa2b78516d710512a3
[W 09:32:41.414 NotebookApp] 404 GET /api/kernels/1f69f8a1-eb9c-4f22-a681-aba214aee59e/channels?session_id=7954275d115d4290870eb66f37139c8a (127.0.0.1): Kernel does not exist: 1f69f8a1-eb9c-4f22-a681-aba214aee59e
[W 09:32:41.441 NotebookApp] 404 GET /api/kernels/1f69f8a1-eb9c-4f22-a681-aba214aee59e/channels?session_id=7954275d115d4290870eb66f37139c8a (127.0.0.1) 36.17ms referer=None
[I 09:33:14.668 NotebookApp] Saving file at /ML_DL/NLP/Untitled.ipynb
[W 09:35:17.391 NotebookApp] Replacing stale connection: 1f69f8a1-eb9c-4f22-a681-aba214aee59e:7954275d115d4290870eb66f37139c8a
[I 09:37:14.650 NotebookApp] Saving file at /ML_DL/NLP/Untitled.ipynb
[W 09:39:44.553 NotebookApp] Replacing stale connection: 1f69f8a1-eb9c-4f22-a681-aba214aee59e:7954275d115d4290870eb66f37139c8a
[C 09:43:13.515 NotebookApp] received signal 15, stopping
[I 09:43:13.515 NotebookApp] Shutting down 0 kernels
[I 09:50:55.012 NotebookApp] [nb_conda_kernels] enabled, 5 kernels found
[I 09:50:55.372 NotebookApp] [nb_conda] enabled
[I 09:50:55.372 NotebookApp] Serving notebooks from local directory: /home/lab15/git_repository/Study
[I 09:50:55.372 NotebookApp] The Jupyter Notebook is running at:
[I 09:50:55.372 NotebookApp] http://ip-172-31-41-188:8895/?token=82136b3e410522c13ea885f98fe7b0cb7d60e4934b38b26c
[I 09:50:55.372 NotebookApp]  or http://127.0.0.1:8895/?token=82136b3e410522c13ea885f98fe7b0cb7d60e4934b38b26c
[I 09:50:55.372 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:50:55.377 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/lab15/.local/share/jupyter/runtime/nbserver-6781-open.html
    Or copy and paste one of these URLs:
        http://ip-172-31-41-188:8895/?token=82136b3e410522c13ea885f98fe7b0cb7d60e4934b38b26c
     or http://127.0.0.1:8895/?token=82136b3e410522c13ea885f98fe7b0cb7d60e4934b38b26c
[W 09:51:08.150 NotebookApp] 404 GET /api/contents/Study/ML_DL?type=directory&_=1584578637705 (127.0.0.1): No such file or directory: Study/ML_DL
[W 09:51:08.151 NotebookApp] No such file or directory: Study/ML_DL
[W 09:51:08.151 NotebookApp] 404 GET /api/contents/Study/ML_DL?type=directory&_=1584578637705 (127.0.0.1) 1.10ms referer=http://127.0.0.1:8895/tree/Study/ML_DL
[W 09:51:09.502 NotebookApp] 404 GET /api/contents/Study/ML_DL?type=directory&_=1584578637706 (127.0.0.1): No such file or directory: Study/ML_DL
[W 09:51:09.502 NotebookApp] No such file or directory: Study/ML_DL
[W 09:51:09.502 NotebookApp] 404 GET /api/contents/Study/ML_DL?type=directory&_=1584578637706 (127.0.0.1) 1.34ms referer=http://127.0.0.1:8895/tree/Study/ML_DL
[W 09:51:09.746 NotebookApp] 404 GET /api/contents/Study/ML_DL?type=directory&_=1584578637707 (127.0.0.1): No such file or directory: Study/ML_DL
[W 09:51:09.746 NotebookApp] No such file or directory: Study/ML_DL
[W 09:51:09.746 NotebookApp] 404 GET /api/contents/Study/ML_DL?type=directory&_=1584578637707 (127.0.0.1) 1.29ms referer=http://127.0.0.1:8895/tree/Study/ML_DL
[W 09:51:10.252 NotebookApp] 404 GET /api/contents/Study?type=directory&_=1584578637708 (127.0.0.1): No such file or directory: Study
[W 09:51:10.252 NotebookApp] No such file or directory: Study
[W 09:51:10.252 NotebookApp] 404 GET /api/contents/Study?type=directory&_=1584578637708 (127.0.0.1) 1.27ms referer=http://127.0.0.1:8895/tree/Study
[W 09:51:11.614 NotebookApp] 404 GET /api/contents/Study?type=directory&_=1584578637709 (127.0.0.1): No such file or directory: Study
[W 09:51:11.614 NotebookApp] No such file or directory: Study
[W 09:51:11.614 NotebookApp] 404 GET /api/contents/Study?type=directory&_=1584578637709 (127.0.0.1) 1.32ms referer=http://127.0.0.1:8895/tree/Study
[W 09:51:11.866 NotebookApp] 404 GET /api/contents/Study?type=directory&_=1584578637710 (127.0.0.1): No such file or directory: Study
[W 09:51:11.866 NotebookApp] No such file or directory: Study
[W 09:51:11.866 NotebookApp] 404 GET /api/contents/Study?type=directory&_=1584578637710 (127.0.0.1) 1.31ms referer=http://127.0.0.1:8895/tree/Study
[W 09:51:12.261 NotebookApp] 404 GET /api/contents/Study?type=directory&_=1584578637711 (127.0.0.1): No such file or directory: Study
[W 09:51:12.261 NotebookApp] No such file or directory: Study
[W 09:51:12.261 NotebookApp] 404 GET /api/contents/Study?type=directory&_=1584578637711 (127.0.0.1) 1.23ms referer=http://127.0.0.1:8895/tree/Study
[W 09:51:12.432 NotebookApp] 404 GET /api/contents/Study?type=directory&_=1584578637712 (127.0.0.1): No such file or directory: Study
[W 09:51:12.432 NotebookApp] No such file or directory: Study
[W 09:51:12.433 NotebookApp] 404 GET /api/contents/Study?type=directory&_=1584578637712 (127.0.0.1) 0.92ms referer=http://127.0.0.1:8895/tree/Study
[W 09:51:54.621 NotebookApp] 404 GET /api/kernels/e1c0f4d1-0089-43f1-bb23-aee4b2fa0569/channels?session_id=fdb3c6e8ac7a4e048e3ea3162e44f710 (127.0.0.1): Kernel does not exist: e1c0f4d1-0089-43f1-bb23-aee4b2fa0569
[W 09:51:54.646 NotebookApp] 404 GET /api/kernels/e1c0f4d1-0089-43f1-bb23-aee4b2fa0569/channels?session_id=fdb3c6e8ac7a4e048e3ea3162e44f710 (127.0.0.1) 32.60ms referer=None
[W 09:52:44.609 NotebookApp] 404 GET /api/contents/Study/ML_DL/NLP/Untitled.ipynb?content=0&_=1584578684193 (127.0.0.1): No such file or directory: Study/ML_DL/NLP/Untitled.ipynb
[W 09:52:44.609 NotebookApp] No such file or directory: Study/ML_DL/NLP/Untitled.ipynb
[W 09:52:44.609 NotebookApp] 404 GET /api/contents/Study/ML_DL/NLP/Untitled.ipynb?content=0&_=1584578684193 (127.0.0.1) 1.30ms referer=http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb
[I 09:52:44.625 NotebookApp] Uploading file to /Study/ML_DL/NLP/Untitled.ipynb
[E 09:52:44.650 NotebookApp] Error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 467, in save
        self._save_notebook(os_path, nb)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[W 09:52:44.653 NotebookApp] 500 PUT /api/contents/Study/ML_DL/NLP/Untitled.ipynb (127.0.0.1): Unexpected error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[W 09:52:44.653 NotebookApp] Unexpected error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[E 09:52:44.653 NotebookApp] {
      "Host": "127.0.0.1:8895",
      "Connection": "keep-alive",
      "Content-Length": "732",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Sec-Fetch-Dest": "empty",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|42d82cea|dc24b2e38c98801b5113d1c95f486302|1582253283",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
      "Content-Type": "application/json",
      "Origin": "http://127.0.0.1:8895",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "ko,en-US;q=0.9,en;q=0.8,ko-KR;q=0.7",
      "Cookie": "_xsrf=2|42d82cea|dc24b2e38c98801b5113d1c95f486302|1582253283; username-127-0-0-1-8888=\"2|1:0|10:1582522590|23:username-127-0-0-1-8888|44:MjczZmFjY2FjMjgxNDg5M2I4ZWQyOGM5MTc1NGUzZWE=|92fdb2039ed09b3dcb465d631d50d85bcf3d1e143ea8719a58af76287db44d27\"; username-127-0-0-1-8896=\"2|1:0|10:1584341366|23:username-127-0-0-1-8896|44:NGViYzFmNzJkMzVmNGRhMmJjMGI4NjNmZDY0NGZhZmY=|8b97988c066161a486a3ba7ad94ced49b08439d696ef4c49ae71f6e4e3b66a52\"; username-127-0-0-1-8895=\"2|1:0|10:1584578637|23:username-127-0-0-1-8895|44:MTcwNjE2OTIwNzgwNGQ1Nzg4MzBhZThmZDc0ODRjNmM=|7f441b9dd10c5750f3703f9c8737b5d8c19c8e94720c49dd848aa4863627846c\""
    }
[E 09:52:44.653 NotebookApp] 500 PUT /api/contents/Study/ML_DL/NLP/Untitled.ipynb (127.0.0.1) 29.22ms referer=http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb
[W 09:54:44.608 NotebookApp] 404 GET /api/contents/Study/ML_DL/NLP/Untitled.ipynb?content=0&_=1584578684194 (127.0.0.1): No such file or directory: Study/ML_DL/NLP/Untitled.ipynb
[W 09:54:44.609 NotebookApp] No such file or directory: Study/ML_DL/NLP/Untitled.ipynb
[W 09:54:44.609 NotebookApp] 404 GET /api/contents/Study/ML_DL/NLP/Untitled.ipynb?content=0&_=1584578684194 (127.0.0.1) 1.31ms referer=http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb
[I 09:54:44.624 NotebookApp] Uploading file to /Study/ML_DL/NLP/Untitled.ipynb
[E 09:54:44.647 NotebookApp] Error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 467, in save
        self._save_notebook(os_path, nb)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[W 09:54:44.647 NotebookApp] 500 PUT /api/contents/Study/ML_DL/NLP/Untitled.ipynb (127.0.0.1): Unexpected error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[W 09:54:44.647 NotebookApp] Unexpected error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[E 09:54:44.648 NotebookApp] {
      "Host": "127.0.0.1:8895",
      "Connection": "keep-alive",
      "Content-Length": "732",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Sec-Fetch-Dest": "empty",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|42d82cea|dc24b2e38c98801b5113d1c95f486302|1582253283",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
      "Content-Type": "application/json",
      "Origin": "http://127.0.0.1:8895",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "ko,en-US;q=0.9,en;q=0.8,ko-KR;q=0.7",
      "Cookie": "_xsrf=2|42d82cea|dc24b2e38c98801b5113d1c95f486302|1582253283; username-127-0-0-1-8888=\"2|1:0|10:1582522590|23:username-127-0-0-1-8888|44:MjczZmFjY2FjMjgxNDg5M2I4ZWQyOGM5MTc1NGUzZWE=|92fdb2039ed09b3dcb465d631d50d85bcf3d1e143ea8719a58af76287db44d27\"; username-127-0-0-1-8896=\"2|1:0|10:1584341366|23:username-127-0-0-1-8896|44:NGViYzFmNzJkMzVmNGRhMmJjMGI4NjNmZDY0NGZhZmY=|8b97988c066161a486a3ba7ad94ced49b08439d696ef4c49ae71f6e4e3b66a52\"; username-127-0-0-1-8895=\"2|1:0|10:1584578637|23:username-127-0-0-1-8895|44:MTcwNjE2OTIwNzgwNGQ1Nzg4MzBhZThmZDc0ODRjNmM=|7f441b9dd10c5750f3703f9c8737b5d8c19c8e94720c49dd848aa4863627846c\""
    }
[E 09:54:44.648 NotebookApp] 500 PUT /api/contents/Study/ML_DL/NLP/Untitled.ipynb (127.0.0.1) 24.22ms referer=http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb
[W 09:56:44.608 NotebookApp] 404 GET /api/contents/Study/ML_DL/NLP/Untitled.ipynb?content=0&_=1584578684195 (127.0.0.1): No such file or directory: Study/ML_DL/NLP/Untitled.ipynb
[W 09:56:44.608 NotebookApp] No such file or directory: Study/ML_DL/NLP/Untitled.ipynb
[W 09:56:44.609 NotebookApp] 404 GET /api/contents/Study/ML_DL/NLP/Untitled.ipynb?content=0&_=1584578684195 (127.0.0.1) 1.28ms referer=http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb
[I 09:56:44.623 NotebookApp] Uploading file to /Study/ML_DL/NLP/Untitled.ipynb
[E 09:56:44.646 NotebookApp] Error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 467, in save
        self._save_notebook(os_path, nb)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[W 09:56:44.646 NotebookApp] 500 PUT /api/contents/Study/ML_DL/NLP/Untitled.ipynb (127.0.0.1): Unexpected error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[W 09:56:44.647 NotebookApp] Unexpected error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[E 09:56:44.647 NotebookApp] {
      "Host": "127.0.0.1:8895",
      "Connection": "keep-alive",
      "Content-Length": "732",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Sec-Fetch-Dest": "empty",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|42d82cea|dc24b2e38c98801b5113d1c95f486302|1582253283",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
      "Content-Type": "application/json",
      "Origin": "http://127.0.0.1:8895",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "ko,en-US;q=0.9,en;q=0.8,ko-KR;q=0.7",
      "Cookie": "_xsrf=2|42d82cea|dc24b2e38c98801b5113d1c95f486302|1582253283; username-127-0-0-1-8888=\"2|1:0|10:1582522590|23:username-127-0-0-1-8888|44:MjczZmFjY2FjMjgxNDg5M2I4ZWQyOGM5MTc1NGUzZWE=|92fdb2039ed09b3dcb465d631d50d85bcf3d1e143ea8719a58af76287db44d27\"; username-127-0-0-1-8896=\"2|1:0|10:1584341366|23:username-127-0-0-1-8896|44:NGViYzFmNzJkMzVmNGRhMmJjMGI4NjNmZDY0NGZhZmY=|8b97988c066161a486a3ba7ad94ced49b08439d696ef4c49ae71f6e4e3b66a52\"; username-127-0-0-1-8895=\"2|1:0|10:1584578637|23:username-127-0-0-1-8895|44:MTcwNjE2OTIwNzgwNGQ1Nzg4MzBhZThmZDc0ODRjNmM=|7f441b9dd10c5750f3703f9c8737b5d8c19c8e94720c49dd848aa4863627846c\""
    }
[E 09:56:44.647 NotebookApp] 500 PUT /api/contents/Study/ML_DL/NLP/Untitled.ipynb (127.0.0.1) 24.49ms referer=http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb
[W 09:58:44.637 NotebookApp] 404 GET /api/contents/Study/ML_DL/NLP/Untitled.ipynb?content=0&_=1584578684196 (127.0.0.1): No such file or directory: Study/ML_DL/NLP/Untitled.ipynb
[W 09:58:44.637 NotebookApp] No such file or directory: Study/ML_DL/NLP/Untitled.ipynb
[W 09:58:44.637 NotebookApp] 404 GET /api/contents/Study/ML_DL/NLP/Untitled.ipynb?content=0&_=1584578684196 (127.0.0.1) 1.32ms referer=http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb
[I 09:58:44.652 NotebookApp] Uploading file to /Study/ML_DL/NLP/Untitled.ipynb
[E 09:58:44.676 NotebookApp] Error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 467, in save
        self._save_notebook(os_path, nb)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[W 09:58:44.676 NotebookApp] 500 PUT /api/contents/Study/ML_DL/NLP/Untitled.ipynb (127.0.0.1): Unexpected error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[W 09:58:44.676 NotebookApp] Unexpected error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[E 09:58:44.677 NotebookApp] {
      "Host": "127.0.0.1:8895",
      "Connection": "keep-alive",
      "Content-Length": "732",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Sec-Fetch-Dest": "empty",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|42d82cea|dc24b2e38c98801b5113d1c95f486302|1582253283",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
      "Content-Type": "application/json",
      "Origin": "http://127.0.0.1:8895",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "ko,en-US;q=0.9,en;q=0.8,ko-KR;q=0.7",
      "Cookie": "_xsrf=2|42d82cea|dc24b2e38c98801b5113d1c95f486302|1582253283; username-127-0-0-1-8888=\"2|1:0|10:1582522590|23:username-127-0-0-1-8888|44:MjczZmFjY2FjMjgxNDg5M2I4ZWQyOGM5MTc1NGUzZWE=|92fdb2039ed09b3dcb465d631d50d85bcf3d1e143ea8719a58af76287db44d27\"; username-127-0-0-1-8896=\"2|1:0|10:1584341366|23:username-127-0-0-1-8896|44:NGViYzFmNzJkMzVmNGRhMmJjMGI4NjNmZDY0NGZhZmY=|8b97988c066161a486a3ba7ad94ced49b08439d696ef4c49ae71f6e4e3b66a52\"; username-127-0-0-1-8895=\"2|1:0|10:1584578637|23:username-127-0-0-1-8895|44:MTcwNjE2OTIwNzgwNGQ1Nzg4MzBhZThmZDc0ODRjNmM=|7f441b9dd10c5750f3703f9c8737b5d8c19c8e94720c49dd848aa4863627846c\""
    }
[E 09:58:44.677 NotebookApp] 500 PUT /api/contents/Study/ML_DL/NLP/Untitled.ipynb (127.0.0.1) 26.42ms referer=http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb
[W 10:00:44.614 NotebookApp] 404 GET /api/contents/Study/ML_DL/NLP/Untitled.ipynb?content=0&_=1584578684197 (127.0.0.1): No such file or directory: Study/ML_DL/NLP/Untitled.ipynb
[W 10:00:44.614 NotebookApp] No such file or directory: Study/ML_DL/NLP/Untitled.ipynb
[W 10:00:44.614 NotebookApp] 404 GET /api/contents/Study/ML_DL/NLP/Untitled.ipynb?content=0&_=1584578684197 (127.0.0.1) 1.37ms referer=http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb
[I 10:00:44.627 NotebookApp] Uploading file to /Study/ML_DL/NLP/Untitled.ipynb
[E 10:00:44.650 NotebookApp] Error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 467, in save
        self._save_notebook(os_path, nb)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/home/ubuntu/anaconda3/envs/yong_ju/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[W 10:00:44.650 NotebookApp] 500 PUT /api/contents/Study/ML_DL/NLP/Untitled.ipynb (127.0.0.1): Unexpected error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[W 10:00:44.651 NotebookApp] Unexpected error while saving file: Study/ML_DL/NLP/Untitled.ipynb [Errno 2] No such file or directory: '/home/lab15/git_repository/Study/Study/ML_DL/NLP/Untitled.ipynb'
[E 10:00:44.651 NotebookApp] {
      "Host": "127.0.0.1:8895",
      "Connection": "keep-alive",
      "Content-Length": "732",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Sec-Fetch-Dest": "empty",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|42d82cea|dc24b2e38c98801b5113d1c95f486302|1582253283",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
      "Content-Type": "application/json",
      "Origin": "http://127.0.0.1:8895",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "ko,en-US;q=0.9,en;q=0.8,ko-KR;q=0.7",
      "Cookie": "_xsrf=2|42d82cea|dc24b2e38c98801b5113d1c95f486302|1582253283; username-127-0-0-1-8888=\"2|1:0|10:1582522590|23:username-127-0-0-1-8888|44:MjczZmFjY2FjMjgxNDg5M2I4ZWQyOGM5MTc1NGUzZWE=|92fdb2039ed09b3dcb465d631d50d85bcf3d1e143ea8719a58af76287db44d27\"; username-127-0-0-1-8896=\"2|1:0|10:1584341366|23:username-127-0-0-1-8896|44:NGViYzFmNzJkMzVmNGRhMmJjMGI4NjNmZDY0NGZhZmY=|8b97988c066161a486a3ba7ad94ced49b08439d696ef4c49ae71f6e4e3b66a52\"; username-127-0-0-1-8895=\"2|1:0|10:1584578637|23:username-127-0-0-1-8895|44:MTcwNjE2OTIwNzgwNGQ1Nzg4MzBhZThmZDc0ODRjNmM=|7f441b9dd10c5750f3703f9c8737b5d8c19c8e94720c49dd848aa4863627846c\""
    }
[E 10:00:44.651 NotebookApp] 500 PUT /api/contents/Study/ML_DL/NLP/Untitled.ipynb (127.0.0.1) 24.29ms referer=http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb
[W 10:01:53.693 NotebookApp] 404 GET /api/contents/Study?type=directory&_=1584578637715 (127.0.0.1): No such file or directory: Study
[W 10:01:53.694 NotebookApp] No such file or directory: Study
[W 10:01:53.694 NotebookApp] 404 GET /api/contents/Study?type=directory&_=1584578637715 (127.0.0.1) 1.35ms referer=http://127.0.0.1:8895/tree/Study
[W 10:01:53.695 NotebookApp] 404 GET /api/contents/Study?type=directory&_=1584578637716 (127.0.0.1): No such file or directory: Study
[W 10:01:53.695 NotebookApp] No such file or directory: Study
[W 10:01:53.695 NotebookApp] 404 GET /api/contents/Study?type=directory&_=1584578637716 (127.0.0.1) 0.90ms referer=http://127.0.0.1:8895/tree/Study
[W 10:02:04.684 NotebookApp] Replacing stale connection: e1c0f4d1-0089-43f1-bb23-aee4b2fa0569:fdb3c6e8ac7a4e048e3ea3162e44f710
[I 10:02:29.840 NotebookApp] Creating new notebook in /ML_DL/Keras_book
[I 10:02:31.164 NotebookApp] Kernel started: 0108c78f-d2d4-4ed3-ba1c-d6cb848571e3
[W 10:02:33.390 NotebookApp] 404 GET /api/contents/Study/ML_DL/NLP/Untitled.ipynb?content=0&_=1584578684198 (127.0.0.1): No such file or directory: Study/ML_DL/NLP/Untitled.ipynb
[W 10:02:33.390 NotebookApp] No such file or directory: Study/ML_DL/NLP/Untitled.ipynb
[W 10:02:33.391 NotebookApp] 404 GET /api/contents/Study/ML_DL/NLP/Untitled.ipynb?content=0&_=1584578684198 (127.0.0.1) 1.44ms referer=http://127.0.0.1:8895/notebooks/Study/ML_DL/NLP/Untitled.ipynb
[I 10:03:17.778 NotebookApp] Kernel shutdown: 0108c78f-d2d4-4ed3-ba1c-d6cb848571e3
[I 10:03:21.363 NotebookApp] Kernel started: d3654868-acf5-43c3-8880-0a78f369e3c9
[I 10:03:45.774 NotebookApp] Kernel started: b1690709-3da4-42bb-b9ce-9ae1d0934ed8
[I 10:04:03.040 NotebookApp] Kernel shutdown: d3654868-acf5-43c3-8880-0a78f369e3c9
[I 10:04:06.678 NotebookApp] Kernel shutdown: b1690709-3da4-42bb-b9ce-9ae1d0934ed8
[W 10:06:04.698 NotebookApp] 404 GET /api/kernels/0108c78f-d2d4-4ed3-ba1c-d6cb848571e3/channels?session_id=b1e9f8bea9814bc7aeed97a281218338 (127.0.0.1): Kernel does not exist: 0108c78f-d2d4-4ed3-ba1c-d6cb848571e3
[W 10:06:04.700 NotebookApp] 404 GET /api/kernels/0108c78f-d2d4-4ed3-ba1c-d6cb848571e3/channels?session_id=b1e9f8bea9814bc7aeed97a281218338 (127.0.0.1) 3.02ms referer=None
[W 10:06:04.725 NotebookApp] 404 GET /api/kernels/d3654868-acf5-43c3-8880-0a78f369e3c9/channels?session_id=e7212fb3be0f43368641e8c161da43f9 (127.0.0.1): Kernel does not exist: d3654868-acf5-43c3-8880-0a78f369e3c9
[W 10:06:04.726 NotebookApp] 404 GET /api/kernels/d3654868-acf5-43c3-8880-0a78f369e3c9/channels?session_id=e7212fb3be0f43368641e8c161da43f9 (127.0.0.1) 2.78ms referer=None
[W 10:06:04.753 NotebookApp] 404 GET /api/kernels/b1690709-3da4-42bb-b9ce-9ae1d0934ed8/channels?session_id=9d1e7d0c6ca047c0b18614032b3ab8d8 (127.0.0.1): Kernel does not exist: b1690709-3da4-42bb-b9ce-9ae1d0934ed8
[W 10:06:04.754 NotebookApp] 404 GET /api/kernels/b1690709-3da4-42bb-b9ce-9ae1d0934ed8/channels?session_id=9d1e7d0c6ca047c0b18614032b3ab8d8 (127.0.0.1) 3.64ms referer=None
[I 10:11:58.218 NotebookApp] Kernel started: d6e4536d-3b4d-46d0-96ec-22915091852f
[I 10:12:19.929 NotebookApp] Kernel started: 5babd0f0-b632-4f0c-9cd7-0f8028e0072c
[I 10:12:50.755 NotebookApp] Starting buffering for 5babd0f0-b632-4f0c-9cd7-0f8028e0072c:21629eb336d144c890d259063da39c9c
[I 10:12:55.049 NotebookApp] Kernel shutdown: 5babd0f0-b632-4f0c-9cd7-0f8028e0072c
[W 10:12:55.051 NotebookApp] delete /ML_DL/Keras_book/Untitled.ipynb
[I 10:12:58.221 NotebookApp] Starting buffering for d6e4536d-3b4d-46d0-96ec-22915091852f:fd3e170f66ed47088da875f14e346519
[I 11:33:19.393 NotebookApp] Kernel started: 71941f86-752d-46af-8d7e-c2d77fa3e828
[I 11:33:24.056 NotebookApp] Starting buffering for 71941f86-752d-46af-8d7e-c2d77fa3e828:26650f149fb94750a1ec8dc0481850fc
[W 13:24:11.991 NotebookApp] Notebook ML_DL/Deep_Learning/jupyter_notebook/`20.03.10 NLP_practice.ipynb is not trusted
[I 13:24:13.545 NotebookApp] Kernel started: 252f902c-23ad-40de-a0a0-8e2d1fcebf58
[W 13:25:44.066 NotebookApp] WebSocket ping timeout after 90000 ms.
[I 13:25:49.071 NotebookApp] Starting buffering for 252f902c-23ad-40de-a0a0-8e2d1fcebf58:336be98678324d308491647b1cde870d
[W 13:25:53.885 NotebookApp] WebSocket ping timeout after 119995 ms.
[I 13:25:58.886 NotebookApp] Starting buffering for d6e4536d-3b4d-46d0-96ec-22915091852f:8af39c284390400c8c3d4e1c01be8aff
[I 13:26:18.813 NotebookApp] Saving file at /ML_DL/Deep_Learning/jupyter_notebook/`20.03.10 NLP_practice.ipynb
[W 13:26:18.814 NotebookApp] Notebook ML_DL/Deep_Learning/jupyter_notebook/`20.03.10 NLP_practice.ipynb is not trusted
[I 13:26:19.801 NotebookApp] Restoring connection for 252f902c-23ad-40de-a0a0-8e2d1fcebf58:336be98678324d308491647b1cde870d
[I 13:26:20.276 NotebookApp] Restoring connection for d6e4536d-3b4d-46d0-96ec-22915091852f:8af39c284390400c8c3d4e1c01be8aff
[I 13:26:41.065 NotebookApp] Kernel interrupted: 252f902c-23ad-40de-a0a0-8e2d1fcebf58
[I 13:28:15.572 NotebookApp] Saving file at /ML_DL/Deep_Learning/jupyter_notebook/`20.03.10 NLP_practice.ipynb
[W 13:28:15.573 NotebookApp] Notebook ML_DL/Deep_Learning/jupyter_notebook/`20.03.10 NLP_practice.ipynb is not trusted
[I 13:30:13.577 NotebookApp] Saving file at /ML_DL/Deep_Learning/jupyter_notebook/`20.03.10 NLP_practice.ipynb
[W 13:30:13.578 NotebookApp] Notebook ML_DL/Deep_Learning/jupyter_notebook/`20.03.10 NLP_practice.ipynb is not trusted
[W 13:32:19.803 NotebookApp] WebSocket ping timeout after 119997 ms.
[W 13:32:20.278 NotebookApp] WebSocket ping timeout after 119997 ms.
[I 13:32:24.806 NotebookApp] Starting buffering for 252f902c-23ad-40de-a0a0-8e2d1fcebf58:336be98678324d308491647b1cde870d
[I 13:32:25.279 NotebookApp] Starting buffering for d6e4536d-3b4d-46d0-96ec-22915091852f:8af39c284390400c8c3d4e1c01be8aff
[I 15:29:01.466 NotebookApp] Restoring connection for d6e4536d-3b4d-46d0-96ec-22915091852f:8af39c284390400c8c3d4e1c01be8aff
[W 15:29:32.063 NotebookApp] Notebook ML_DL/Deep_Learning/jupyter_notebook/`20.03.10 NLP_practice.ipynb is not trusted
[I 15:30:36.013 NotebookApp] Saving file at /ML_DL/Deep_Learning/jupyter_notebook/`20.03.10 NLP_practice.ipynb
[W 15:30:36.013 NotebookApp] Notebook ML_DL/Deep_Learning/jupyter_notebook/`20.03.10 NLP_practice.ipynb is not trusted
[I 15:57:48.909 NotebookApp] Kernel shutdown: d6e4536d-3b4d-46d0-96ec-22915091852f
[W 15:57:48.915 NotebookApp] delete /ML_DL/Deep_Learning/Natural Language Processing/ex_RNN.ipynb
[W 15:57:58.006 NotebookApp] delete /ML_DL/Deep_Learning/Natural Language Processing
[W 15:58:07.905 NotebookApp] delete /ML_DL/NLP/Untitled.ipynb
[I 15:58:10.993 NotebookApp] Kernel started: 7ea8c54d-c77b-4899-9157-958bff1a6d64
